export const GET_POKEMONS_START = "GET_POKEMONS_START";
export const GET_POKEMONS_ERROR = "GET_POKEMONS_ERROR";
export const GET_POKEMONS_COMPLETED = "GET_POKEMONS_COMPLETED";
export const GET_POKEMONS_RESET = "GET_POKEMONS_RESET";